plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/meastman/Development/business-value/lindsay-lodge"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]